### ISSUE TITLE
WCMIO_SLING plugin cannot be loaded in SlingContext(Impl), only in AemContext(Impl)

### ISSUE THREAD

**Issue by henrykuijpers** [wcm-io/io.wcm.testing.wcm-io-mock.sling#2]
It would be nice to be able to load the WCMIO_SLING plugin in a "vanilla" SlingContext, without AemContext capabilities. There should be no reason that AemContext is required for the use of Sling features.

**Comment by stefanseifert** [comment]
yes, this could be changed as SlingContext should be enough for this plugin.

however, currently the "plugin" method of all *ContextBuilder implementations is like this:
https://github.com/apache/sling-org-apache-sling-testing-sling-mock/blob/9947f435d559dda511b550449086148817b7f948/junit5/src/main/java/org/apache/sling/testing/mock/sling/junit5/SlingContextBuilder.java#L67-L76

this has the limitation, that all plugins that are put into one method call have to be based on sample *ContextImpl type as the others - otherwise you get a compilation error. usage example:
https://github.com/wcm-io/io.wcm.samples/blob/c085c911cc62e955027b6748deac0fea9db2fc27/bundles/core/src/test/java/io/wcm/samples/core/testcontext/AppAemContext.java#L57

so, if we simply change this, all users of this plugin would have to change their code. to avoid this, we additionally should change the implementation of the "plugin" method to accept all types of plugins in a single line (should done this first-hand). this would need PRs vor osgi-mock, sling-mock and aem-mock.

**Comment by henrykuijpers** [comment]
Yes, I agree that there are some issues with the current setup in OSGi/Sling/AEM mocks. I've seen this ticket as well: https://issues.apache.org/jira/browse/SLING-8312 Maybe it's one that we would also want to fix?

I honestly don't know right now how the plugin-method could be fixed. I think there will be issues with the Java language and how it handles generics and boundaries etc. What would your suggested fix be?

**Comment by stefanseifert** [comment]
i think the use case with mixing different plugin types can be easily fixed be changing the signature from 
```java
public final <T extends OsgiContextImpl> SlingContextBuilder plugin(@NotNull ContextPlugin<T> @NotNull ... plugin) {
```
to
```java
public final SlingContextBuilder plugin(@NotNull ContextPlugin<? extends OsgiContextImpl> @NotNull ... plugin) {
```

**Comment by stefanseifert** [comment]
with preparing the ground with https://issues.apache.org/jira/browse/SLING-11792 and https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/7 we can move forward here, i've prepared https://github.com/wcm-io/io.wcm.testing.wcm-io-mock.sling/pull/3
